source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem "mongoid", "~> 3.0.0"
gem 'bson_ext', '~> 1.5'
gem 'bcrypt-ruby', '~> 3.0.0'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'compass-rails'

  gem 'haml_coffee_assets'
  gem 'execjs'

  gem 'rails-backbone'
  gem 'marionette-rails'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'haml-rails'

gem 'rabl'
